name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build Distribution
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      
      - name: Build package
        run: python -m build
      
      - name: Store distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/justllms
    
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  github-release:
    name: Create GitHub Release
    needs: publish-pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Extract changelog
        id: changelog
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          CHANGELOG=$(awk "/## \[$VERSION\]/{flag=1; next} /## \[/{flag=0} flag" CHANGELOG.md)
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.version.outputs.VERSION }}
          body: |
            ## JustLLMs v${{ steps.version.outputs.VERSION }}
            
            ### Installation
            ```bash
            pip install justllms==${{ steps.version.outputs.VERSION }}
            ```
            
            ### What's Changed
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            ### Full Changelog
            https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md
            
            ---
            *View on PyPI: https://pypi.org/project/justllms/${{ steps.version.outputs.VERSION }}/*
          files: dist/*
          draft: false
          prerelease: false

  verify-release:
    name: Verify Release
    needs: publish-pypi
    runs-on: ubuntu-latest
    
    steps:
      - name: Wait for PyPI availability
        run: sleep 30
      
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Test installation from PyPI
        run: |
          python -m pip install --upgrade pip
          pip install justllms==${{ steps.version.outputs.VERSION }}
          python -c "import justllms; assert justllms.__version__ == '${{ steps.version.outputs.VERSION }}'"
          echo "✅ Release verified successfully!"